imports_layout = "HorizontalVertical"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
edition = "2018"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
wrap_comments = true
